name: Deploy to AWS Lambda

on:
  push:
    branches: [ main ]  # main 브랜치에 push될 때 실행
  pull_request:
    branches: [ main ]  # main 브랜치로의 PR이 생성될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
    
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          pip install aws-lambda-builders
    
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
    
      - name: Create deployment package
        run: |
          mkdir -p deployment
          
          # code 디렉토리의 모든 Python 파일을 deployment 폴더로 복사
          cp -r code/*.py deployment/
          
          # requirements.txt 파일을 deployment 폴더로 복사
          cp requirements.txt deployment/
          
          # deployment 폴더로 이동
          cd deployment

          # deployment 폴더의 모든 파일을 압축
          zip -r ../deployment-package.zip .
      
      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
          --function-name homepage-builder-main \
          --zip-file fileb://deployment-package.zip